[options]

db_host = pg
db_port = 5432
db_user = odoo
db_password = odoo123
db_name = odoo

addons_path = /mnt/extra-addons
data_dir = /etc/odoo

admin_passwd = odoo-super-user
logfile = /etc/odoo/odoo-server.log
dev_mode = reload

; ------
; --proxy-mode | Activate reverse proxy WSGI wrappers (headers rewriting) Only enable this when running behind a trusted web proxy!
; ------
proxy_mode = True
